version: '3.7'
services:
  postgres:
    container_name: postgresdb
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  app:
    container_name: app
    restart: always
    build: .
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - ${PORT}:${PORT}
    external_links:
      - postgres
    depends_on:
      - postgres
